apiVersion: v1
kind: Service
metadata:
  name: for-doc-service
  labels:
    app: for-doc
spec:
  selector:
    app: for-doc
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 80
  type: ClusterIP