name: CI/CD Pipeline for FOR-DOC

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Set up Minikube
      uses: medyagh/setup-minikube@latest
      with:
        driver: docker

    - name: Build Docker Image for FOR-DOC
      run: |
        docker build -t for-doc:latest .

    - name: Load Docker Image into Minikube
      run: |
        minikube image load for-doc:latest

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

    - name: Verify Deployment
      run: |
        kubectl rollout status deployment/for-doc-deployment
