jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Build Backend with Maven
      run: |
        cd Java/VIA-Tabloid
        mvn clean package -DskipTests

    - name: Set up Minikube
      uses: medyagh/setup-minikube@latest
      with:
        driver: docker

    - name: Build Docker Image
      run: |
        docker build -t for-doc:latest .

    - name: Load Image into Minikube
      run: |
        minikube image load for-doc:latest

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml
        kubectl apply -f service.yaml

    - name: Verify Deployment
      run: |
        kubectl rollout status deployment/for-doc-deployment
